import { AppHeader } from "@/components/AppHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { trpc } from "@/lib/trpc";
import { Download, FileUp, Upload } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function CsvPage() {
  const [type, setType] = useState<"formula" | "event">("formula"); const [file, setFile] = useState<File | null>(null); const utils = trpc.useUtils();
  const exportData = trpc.baccarat.csv.exportData.useQuery(undefined, { enabled: false });
  const importData = trpc.baccarat.csv.importData.useMutation({ onSuccess: result => { toast.success(`匯入完成：${result.imported} 筆；略過重複資料 ${result.skipped} 筆。`); setFile(null); utils.baccarat.storage.formulaList.invalidate(); utils.baccarat.storage.eventList.invalidate(); }, onError: error => toast.error(error.message) });
  const download = async (exportType: "formula" | "event") => { const result = await exportData.refetch(); if (!result.data) return; const contents = exportType === "formula" ? result.data.formulaCsv : result.data.eventCsv; const blob = new Blob([contents], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = exportType === "formula" ? "formula_temp.csv" : "event_storage.csv"; anchor.click(); URL.revokeObjectURL(url); toast.success("CSV 已匯出。 "); };
  const upload = () => { if (!file) return; const reader = new FileReader(); reader.onload = () => importData.mutate({ type, csv: String(reader.result ?? "") }); reader.onerror = () => toast.error("無法讀取 CSV 檔案。"); reader.readAsText(file, "utf-8"); };
  return <div className="mx-auto max-w-[1100px]"><AppHeader eyebrow="CSVMANAGER.PY" title="CSV 匯入與匯出" description="完全依 CsvManager.py 的欄位順序、UTF-8 BOM 與 formulas JSON 序列化規則，移轉公式與事件資料。" /><div className="grid gap-5 lg:grid-cols-2"><Card className="rounded-2xl border-[#E7EAF0] bg-white shadow-[0_8px_28px_rgba(21,36,59,0.045)]"><CardContent className="p-6"><div className="flex size-11 items-center justify-center rounded-xl bg-[#EFF6FF] text-[#1C69B3]"><Download className="size-5" /></div><p className="mt-5 text-xs font-bold tracking-[0.15em] text-[#A27C2E]">EXPORT</p><h2 className="mt-2 font-serif text-2xl font-semibold text-[#15243B]">匯出資料</h2><p className="mt-2 text-sm leading-6 text-slate-500">輸出目前帳號所有 MySQL 資料，檔案名稱與來源 CSV 模組一致。</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><Button className="h-11 bg-[#15243B] text-white hover:bg-[#213856]" onClick={() => download("formula")} disabled={exportData.isFetching}><Download className="size-4" />公式 CSV</Button><Button variant="outline" className="h-11 border-[#E2E7EE] bg-white" onClick={() => download("event")} disabled={exportData.isFetching}><Download className="size-4" />事件 CSV</Button></div></CardContent></Card><Card className="rounded-2xl border-[#E7EAF0] bg-white shadow-[0_8px_28px_rgba(21,36,59,0.045)]"><CardContent className="p-6"><div className="flex size-11 items-center justify-center rounded-xl bg-[#FFF8EA] text-[#9B7228]"><FileUp className="size-5" /></div><p className="mt-5 text-xs font-bold tracking-[0.15em] text-[#A27C2E]">IMPORT</p><h2 className="mt-2 font-serif text-2xl font-semibold text-[#15243B]">匯入資料</h2><p className="mt-2 text-sm leading-6 text-slate-500">重複的桌號與局數／事件模式將自動略過，避免重複存入。</p><Tabs value={type} onValueChange={value => setType(value as "formula" | "event")} className="mt-5"><TabsList className="bg-[#F2F4F7]"><TabsTrigger value="formula" className="data-[state=active]:bg-[#15243B] data-[state=active]:text-white">公式資料</TabsTrigger><TabsTrigger value="event" className="data-[state=active]:bg-[#15243B] data-[state=active]:text-white">事件資料</TabsTrigger></TabsList></Tabs><Input type="file" accept=".csv,text/csv" className="mt-4 h-11 border-[#E2E7EE] file:mr-3 file:rounded-md file:border-0 file:bg-[#F2F4F7] file:px-3 file:py-1.5 file:text-xs file:font-semibold file:text-[#15243B]" onChange={event => setFile(event.target.files?.[0] ?? null)} /><Button className="mt-3 h-11 w-full bg-[#15243B] text-white hover:bg-[#213856]" onClick={upload} disabled={!file || importData.isPending}><Upload className="size-4" />{importData.isPending ? "匯入中" : "開始匯入"}</Button></CardContent></Card></div></div>;
}
