import { AppHeader } from "@/components/AppHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { trpc } from "@/lib/trpc";
import type { CustomFormulaRule, ArithmeticOperator, SourceKind, SourceSide } from "../../../server/customFormula";
import { BookOpenCheck, ChevronRight, CirclePlus, CopyPlus, Equal, Info, Minus, Plus, SlidersHorizontal, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

const CARD_LABELS = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"];
const OPERATORS: ArithmeticOperator[] = ["+", "-", "*", "/"];
const SOURCE_LABELS: Record<SourceKind, string> = { point: "點數", card1: "第 1 張牌", card2: "第 2 張牌", card3: "第 3 張牌" };

function numberValue(value: string) { const parsed = Number(value); return Number.isFinite(parsed) ? Math.max(-1000, Math.min(1000, parsed)) : 0; }
function operationSymbol(operation: ArithmeticOperator) { return operation === "+" ? Plus : operation === "-" ? Minus : operation === "*" ? "×" : "÷"; }

export default function CustomFormulasPage() {
  const utils = trpc.useUtils();
  const defaults = trpc.baccarat.customFormulas.defaults.useQuery();
  const formulas = trpc.baccarat.customFormulas.list.useQuery();
  const [name, setName] = useState("");
  const [rule, setRule] = useState<CustomFormulaRule | null>(null);
  useEffect(() => { if (defaults.data && !rule) setRule(defaults.data); }, [defaults.data, rule]);
  const create = trpc.baccarat.customFormulas.create.useMutation({
    onSuccess: () => { toast.success("自訂公式已建立，可在分析頁套用。"); setName(""); if (defaults.data) setRule(defaults.data); utils.baccarat.customFormulas.list.invalidate(); },
    onError: error => toast.error(error.message),
  });
  const setEnabled = trpc.baccarat.customFormulas.setEnabled.useMutation({ onSuccess: () => utils.baccarat.customFormulas.list.invalidate(), onError: error => toast.error(error.message) });
  const remove = trpc.baccarat.customFormulas.remove.useMutation({ onSuccess: () => { toast.success("已刪除新公式。"); utils.baccarat.customFormulas.list.invalidate(); }, onError: error => toast.error(error.message) });

  if (defaults.isError) return <div className="mx-auto max-w-[1440px]"><AppHeader eyebrow="CUSTOM FORMULA" title="自訂公式" description="安全規則編輯器暫時無法載入。" /><Card className="rounded-2xl border-[#F1DADA] bg-white"><CardContent className="p-6"><p className="text-sm text-[#B64A4A]">無法取得自訂公式的預設規則，請重新嘗試。</p><Button className="mt-4 bg-[#15243B] text-white hover:bg-[#213856]" onClick={() => defaults.refetch()}>重新載入</Button></CardContent></Card></div>;
  if (!rule) return <div className="mx-auto max-w-[1440px]"><AppHeader eyebrow="CUSTOM FORMULA" title="自訂公式" description="正在載入安全規則編輯器…" /><FormulaSkeleton /></div>;
  const update = (updater: (current: CustomFormulaRule) => CustomFormulaRule) => setRule(current => current ? updater(current) : current);
  const updateTerm = (key: "playerCard" | "bankerCard" | "playerPoint" | "bankerPoint" | "round", property: string, value: unknown) => update(current => ({ ...current, [key]: { ...current[key], [property]: value } } as CustomFormulaRule));
  const updateWeight = (key: "sharedCardWeights" | "playerCardWeights" | "bankerCardWeights" | "playerPoint" | "bankerPoint", index: number, value: number) => update(current => key === "playerPoint" || key === "bankerPoint" ? ({ ...current, [key]: { ...current[key], weights: { ...current[key].weights, [index]: value } } } as CustomFormulaRule) : ({ ...current, [key]: { ...current[key], [index]: value } } as CustomFormulaRule));
  const addPrevious = () => update(current => ({ ...current, previousExpressions: [...current.previousExpressions, { enabled: true, left: { side: "player", kind: "point" }, operator: "-", right: { side: "banker", kind: "point" }, absolute: true, operation: "+", coefficient: 1 }] }));
  const updatePrevious = (index: number, field: string, value: unknown) => update(current => ({ ...current, previousExpressions: current.previousExpressions.map((expression, expressionIndex) => expressionIndex === index ? { ...expression, [field]: value } : expression) }));
  const updateSource = (index: number, side: "left" | "right", field: "side" | "kind", value: SourceSide | SourceKind) => update(current => ({ ...current, previousExpressions: current.previousExpressions.map((expression, expressionIndex) => expressionIndex === index ? { ...expression, [side]: { ...expression[side], [field]: value } } : expression) }));

  return <div className="mx-auto max-w-[1440px] pb-10">
    <AppHeader eyebrow="CUSTOM FORMULA" title="自訂公式管理" description="由可驗證的資料來源組成新公式；內建的 Formula.py 十八項公式完全保留、不會被覆寫。" action={<Badge className="rounded-full border border-[#E8D9B5] bg-[#FFF9EB] px-3 py-1.5 text-[#94702B] hover:bg-[#FFF9EB]"><BookOpenCheck className="mr-1.5 size-3.5" />安全規則運算</Badge>} />
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
      <div className="space-y-5">
        <Card className="overflow-hidden rounded-2xl border-[#E7EAF0] bg-white shadow-[0_8px_28px_rgba(21,36,59,0.045)]"><CardContent className="p-5 sm:p-6">
          <SectionTitle index="01" title="新公式名稱" description="建立的規則會獨立儲存，絕不修改 Formula.py 的原始公式。" />
          <div className="mt-5 flex flex-col gap-3 sm:flex-row"><Input value={name} onChange={event => setName(event.target.value)} maxLength={100} placeholder="例如：前局差額牌面加權" className="h-11 border-[#E2E7EE] bg-[#FCFDFE]" /><Button onClick={() => create.mutate({ name, rules: rule })} disabled={!name.trim() || create.isPending} className="h-11 bg-[#15243B] text-white hover:bg-[#213856]"><CirclePlus className="size-4" />{create.isPending ? "建立中" : "儲存新公式"}</Button></div>
        </CardContent></Card>

        <Card className="rounded-2xl border-[#E7EAF0] bg-white shadow-[0_8px_28px_rgba(21,36,59,0.045)]"><CardContent className="p-5 sm:p-6">
          <SectionTitle index="02" title="牌面點數來源" description="A 至 K 的牌面可設定權重，並以指定的四則運算併入公式總值。" />
          <div className="mt-5 flex flex-col gap-3 rounded-xl border border-[#ECEFF4] bg-[#FAFBFC] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-[#15243B]">閒／莊牌面權重模式</p><p className="mt-1 text-xs text-slate-500">共用時使用同一組 A–K 權重；獨立時可個別編輯閒、莊權重。</p></div><div className="flex rounded-lg border border-[#E4E8EE] bg-white p-1"><button type="button" onClick={() => update(current => ({ ...current, cardWeightMode: "shared" }))} className={`rounded-md px-3 py-1.5 text-xs font-semibold ${rule.cardWeightMode === "shared" ? "bg-[#15243B] text-white" : "text-slate-500"}`}>共用</button><button type="button" onClick={() => update(current => ({ ...current, cardWeightMode: "independent" }))} className={`rounded-md px-3 py-1.5 text-xs font-semibold ${rule.cardWeightMode === "independent" ? "bg-[#15243B] text-white" : "text-slate-500"}`}>各自獨立</button></div></div>
          <div className={`mt-4 grid gap-4 ${rule.cardWeightMode === "independent" ? "lg:grid-cols-2" : ""}`}>{rule.cardWeightMode === "shared" ? <WeightGrid title="共用牌面權重" labels={CARD_LABELS} weights={rule.sharedCardWeights} color="gold" onChange={(index, value) => updateWeight("sharedCardWeights", index, value)} /> : <><WeightGrid title="閒方牌面權重" labels={CARD_LABELS} weights={rule.playerCardWeights} color="blue" onChange={(index, value) => updateWeight("playerCardWeights", index, value)} /><WeightGrid title="莊方牌面權重" labels={CARD_LABELS} weights={rule.bankerCardWeights} color="red" onChange={(index, value) => updateWeight("bankerCardWeights", index, value)} /></>}</div>
          <div className="mt-4 grid gap-3 lg:grid-cols-2"><TermPanel title="閒方牌面" description="可計算全部或指定張數的牌面權重合計。" term={rule.playerCard} onChange={(field, value) => updateTerm("playerCard", field, value)} showPosition /><TermPanel title="莊方牌面" description="可計算全部或指定張數的牌面權重合計。" term={rule.bankerCard} onChange={(field, value) => updateTerm("bankerCard", field, value)} showPosition /></div>
        </CardContent></Card>

        <Card className="rounded-2xl border-[#E7EAF0] bg-white shadow-[0_8px_28px_rgba(21,36,59,0.045)]"><CardContent className="p-5 sm:p-6">
          <SectionTitle index="03" title="本局點數與局數來源" description="閒、莊計算後點數 0–9 各自擁有權重，局數可作為另一個可選來源。" />
          <div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="space-y-3"><WeightGrid title="閒點數權重（0–9）" labels={Array.from({ length: 10 }, (_, index) => String(index))} weights={rule.playerPoint.weights} color="blue" onChange={(index, value) => updateWeight("playerPoint", index, value)} /><TermPanel title="閒點數" description="以本局閒方計算後的點數取得對應權重。" term={rule.playerPoint} onChange={(field, value) => updateTerm("playerPoint", field, value)} /></div><div className="space-y-3"><WeightGrid title="莊點數權重（0–9）" labels={Array.from({ length: 10 }, (_, index) => String(index))} weights={rule.bankerPoint.weights} color="red" onChange={(index, value) => updateWeight("bankerPoint", index, value)} /><TermPanel title="莊點數" description="以本局莊方計算後的點數取得對應權重。" term={rule.bankerPoint} onChange={(field, value) => updateTerm("bankerPoint", field, value)} /></div></div>
          <div className="mt-4"><TermPanel title="局數" description="使用目前局次乘上係數後，併入公式總值。" term={rule.round} onChange={(field, value) => updateTerm("round", field, value)} /></div>
        </CardContent></Card>

        <Card className="rounded-2xl border-[#E7EAF0] bg-white shadow-[0_8px_28px_rgba(21,36,59,0.045)]"><CardContent className="p-5 sm:p-6">
          <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><SectionTitle index="04" title="前一局資料雙來源運算" description="來源 A、來源 B 分別選取前局閒／莊點數或第 1–3 張牌，再用四則運算、絕對差額與係數加入本公式。" /><Button type="button" variant="outline" onClick={addPrevious} className="border-[#D8C487] bg-[#FFF9EB] text-[#82631F] hover:bg-[#FFF4D8]"><CopyPlus className="size-4" />加入前局資料</Button></div>
          <div className="mt-5 space-y-4">{rule.previousExpressions.length === 0 ? <div className="rounded-xl border border-dashed border-[#DFE5EC] bg-[#FAFBFC] p-5 text-sm leading-6 text-slate-500">尚未加入前一局資料。若需前局閒、莊點數或指定牌面差額／相乘，請點選右上方按鈕。</div> : rule.previousExpressions.map((expression, index) => <PreviousExpression key={index} index={index} expression={expression} onChange={updatePrevious} onSourceChange={updateSource} onRemove={() => update(current => ({ ...current, previousExpressions: current.previousExpressions.filter((_, expressionIndex) => expressionIndex !== index) }))} />)}</div>
        </CardContent></Card>

        <Card className="rounded-2xl border-[#E7EAF0] bg-white shadow-[0_8px_28px_rgba(21,36,59,0.045)]"><CardContent className="p-5 sm:p-6"><SectionTitle index="05" title="最終預測條件" description="所有啟用來源運算後產生結果值；結果大於、低於或等於零時分別依下列規則預測。" /><div className="mt-5 grid gap-3 md:grid-cols-3"><Condition label="結果 > 0" value={rule.positivePrediction} onChange={value => update(current => ({ ...current, positivePrediction: value }))} /><Condition label="結果 < 0" value={rule.negativePrediction} onChange={value => update(current => ({ ...current, negativePrediction: value }))} /><Condition label="結果 = 0" value={rule.zeroPrediction} onChange={value => update(current => ({ ...current, zeroPrediction: value }))} /></div></CardContent></Card>
      </div>
      <aside className="space-y-5 xl:sticky xl:top-6 xl:h-fit">
        <Card className="overflow-hidden rounded-2xl border-[#E7EAF0] bg-white shadow-[0_8px_28px_rgba(21,36,59,0.045)]"><CardContent className="p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold tracking-[0.15em] text-[#A27C2E]">SAVED RULES</p><h2 className="mt-1 font-serif text-2xl font-semibold text-[#15243B]">已建立公式</h2></div><SlidersHorizontal className="size-5 text-[#A27C2E]" /></div><p className="mt-3 text-xs leading-5 text-slate-500">啟用中的公式會在「本局分析」完成時計算預測結果。</p><div className="mt-5 space-y-3">{formulas.isLoading ? <FormulaSkeleton compact /> : formulas.isError ? <div className="rounded-xl border border-[#F1DADA] bg-[#FFF9F9] p-4 text-sm leading-6 text-[#B64A4A]">無法讀取已建立公式。<button type="button" onClick={() => formulas.refetch()} className="ml-2 font-bold underline">重新載入</button></div> : formulas.data?.length ? formulas.data.map(formula => <div key={formula.id} className="rounded-xl border border-[#E8EBF0] bg-[#FCFDFE] p-3.5"><div className="flex items-start gap-3"><Switch checked={formula.isEnabled} onCheckedChange={checked => setEnabled.mutate({ id: formula.id, isEnabled: checked })} aria-label={`切換 ${formula.name} 啟用狀態`} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-[#15243B]">{formula.name}</p><p className="mt-1 text-[11px] text-slate-400">{formula.isEnabled ? "已啟用 · 分析頁會計算" : "已停用"}</p></div></div><button type="button" onClick={() => remove.mutate({ id: formula.id })} disabled={remove.isPending} className="mt-3 flex h-8 w-full items-center justify-center gap-1.5 rounded-lg border border-[#F1DADA] bg-white text-xs font-semibold text-[#B64A4A] transition hover:bg-[#FFF1F1]"><Trash2 className="size-3.5" />刪除新公式</button></div>) : <div className="rounded-xl border border-dashed border-[#DFE5EC] bg-[#FAFBFC] p-5 text-sm leading-6 text-slate-500">尚未建立自訂公式。完成左側來源與預測設定後即可儲存。</div>}</div></CardContent></Card>
        <Card className="rounded-2xl border-[#E9DDBE] bg-[#FFFDF8] shadow-[0_8px_28px_rgba(21,36,59,0.035)]"><CardContent className="p-5"><div className="flex gap-3"><Info className="mt-0.5 size-4 shrink-0 text-[#A27C2E]" /><div><p className="text-sm font-bold text-[#705622]">安全運算規則</p><p className="mt-2 text-xs leading-5 text-[#8D7952]">本功能僅接受固定的牌面、點數、局數與前局資料來源，並以白名單四則運算處理；不執行任何任意程式碼。</p></div></div></CardContent></Card>
      </aside>
    </div>
  </div>;
}

function SectionTitle({ index, title, description }: { index: string; title: string; description: string }) { return <div><p className="text-xs font-semibold tracking-[0.15em] text-[#A27C2E]">SOURCE {index}</p><h2 className="mt-1 font-serif text-2xl font-semibold text-[#15243B]">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></div>; }
function FormulaSkeleton({ compact = false }: { compact?: boolean }) { return <div className={`animate-pulse space-y-3 ${compact ? "" : "mt-6"}`}><div className="h-5 w-2/5 rounded bg-slate-100" /><div className="h-16 rounded-xl bg-slate-100" /><div className="h-16 rounded-xl bg-slate-100" /></div>; }
function WeightGrid({ title, labels, weights, color, onChange }: { title: string; labels: string[]; weights: Record<string, number>; color: "blue" | "red" | "gold"; onChange: (index: number, value: number) => void }) { const colorClasses = { blue: "border-[#D7E8F7] bg-[#F8FBFF] text-[#1C69B3]", red: "border-[#F1DADA] bg-[#FFF9F9] text-[#B64A4A]", gold: "border-[#E8D9B5] bg-[#FFFDF8] text-[#8B6A26]" }; return <div className={`rounded-xl border p-4 ${colorClasses[color]}`}><p className="text-sm font-bold">{title}</p><div className="mt-3 grid grid-cols-4 gap-2 sm:grid-cols-7 lg:grid-cols-7">{labels.map((label, index) => <label key={label} className="min-w-0"><span className="mb-1 block text-[10px] font-bold opacity-70">{label}</span><Input aria-label={`${title} ${label} 權重`} type="number" step="0.1" value={weights[String(index + (labels[0] === "0" ? 0 : 1))] ?? 0} onChange={event => onChange(index + (labels[0] === "0" ? 0 : 1), numberValue(event.target.value))} className="h-8 border-white bg-white px-1 text-center text-xs font-semibold text-[#15243B] shadow-sm" /></label>)}</div></div>; }
function TermPanel({ title, description, term, onChange, showPosition = false }: { title: string; description: string; term: { enabled: boolean; operation: ArithmeticOperator; coefficient: number; position?: "all" | 1 | 2 | 3 }; onChange: (field: string, value: unknown) => void; showPosition?: boolean }) { const symbol = operationSymbol(term.operation); return <div className="rounded-xl border border-[#E8EBF0] bg-[#FCFDFE] p-4"><div className="flex gap-3"><Switch checked={term.enabled} onCheckedChange={checked => onChange("enabled", checked)} aria-label={`切換${title}`} /><div><p className="text-sm font-bold text-[#15243B]">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{showPosition && <select value={String(term.position ?? "all")} onChange={event => onChange("position", event.target.value === "all" ? "all" : Number(event.target.value))} className="h-9 rounded-md border border-[#E1E6ED] bg-white px-2 text-xs text-[#40516A]"><option value="all">全部牌面</option><option value="1">第 1 張</option><option value="2">第 2 張</option><option value="3">第 3 張</option></select>}<select value={term.operation} onChange={event => onChange("operation", event.target.value as ArithmeticOperator)} className="h-9 rounded-md border border-[#E1E6ED] bg-white px-2 text-xs font-bold text-[#40516A]"><option value="+">{symbolText(symbol)} 加入</option><option value="-">− 相減</option><option value="*">× 相乘</option><option value="/">÷ 相除</option></select><Input aria-label={`${title} 係數`} type="number" step="0.1" value={term.coefficient} onChange={event => onChange("coefficient", numberValue(event.target.value))} className="h-9 bg-white text-center text-xs" /></div></div>; }
function symbolText(symbol: ReturnType<typeof operationSymbol>) { return typeof symbol === "string" ? symbol : "+"; }
function SourceSelect({ source, onChange }: { source: { side: SourceSide; kind: SourceKind }; onChange: (field: "side" | "kind", value: SourceSide | SourceKind) => void }) { return <span className="grid grid-cols-2 gap-1.5"><select value={source.side} onChange={event => onChange("side", event.target.value as SourceSide)} className="h-9 rounded-md border border-[#E1E6ED] bg-white px-2 text-xs text-[#40516A]"><option value="player">前局閒方</option><option value="banker">前局莊方</option></select><select value={source.kind} onChange={event => onChange("kind", event.target.value as SourceKind)} className="h-9 rounded-md border border-[#E1E6ED] bg-white px-2 text-xs text-[#40516A]">{Object.entries(SOURCE_LABELS).map(([kind, label]) => <option key={kind} value={kind}>{label}</option>)}</select></span>; }
function PreviousExpression({ index, expression, onChange, onSourceChange, onRemove }: { index: number; expression: CustomFormulaRule["previousExpressions"][number]; onChange: (index: number, field: string, value: unknown) => void; onSourceChange: (index: number, side: "left" | "right", field: "side" | "kind", value: SourceSide | SourceKind) => void; onRemove: () => void }) { return <div className="rounded-xl border border-[#E6EAF0] bg-[#FCFDFE] p-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><Switch checked={expression.enabled} onCheckedChange={checked => onChange(index, "enabled", checked)} aria-label={`切換前局資料 ${index + 1}`} /><p className="text-sm font-bold text-[#15243B]">前一局資料 {index + 1}</p></div><button type="button" onClick={onRemove} className="rounded-lg p-1.5 text-slate-400 transition hover:bg-[#FFF1F1] hover:text-[#B64A4A]" aria-label="移除此筆前局資料"><Trash2 className="size-4" /></button></div><div className="mt-4 grid gap-2 lg:grid-cols-[minmax(0,1fr)_70px_minmax(0,1fr)_auto] lg:items-center"><SourceSelect source={expression.left} onChange={(field, value) => onSourceChange(index, "left", field, value)} /><select value={expression.operator} onChange={event => onChange(index, "operator", event.target.value as ArithmeticOperator)} className="h-9 rounded-md border border-[#E1E6ED] bg-white px-2 text-center text-sm font-bold text-[#40516A]">{OPERATORS.map(operator => <option key={operator} value={operator}>{operator === "*" ? "×" : operator === "/" ? "÷" : operator}</option>)}</select><SourceSelect source={expression.right} onChange={(field, value) => onSourceChange(index, "right", field, value)} /><label className="flex h-9 items-center gap-2 whitespace-nowrap text-xs font-medium text-[#53647C]"><input type="checkbox" checked={expression.absolute} onChange={event => onChange(index, "absolute", event.target.checked)} className="accent-[#A27C2E]" />取絕對差額</label></div><div className="mt-3 flex flex-wrap items-center gap-2 rounded-lg bg-[#F4F6F9] p-2.5 text-xs text-[#596981]"><span>再以</span><select value={expression.operation} onChange={event => onChange(index, "operation", event.target.value as ArithmeticOperator)} className="h-8 rounded border border-[#E1E6ED] bg-white px-2 text-xs font-bold"><option value="+">＋ 加入總值</option><option value="-">− 扣除</option><option value="*">× 相乘</option><option value="/">÷ 相除</option></select><span>係數</span><Input aria-label="前局資料係數" type="number" step="0.1" value={expression.coefficient} onChange={event => onChange(index, "coefficient", numberValue(event.target.value))} className="h-8 w-20 bg-white text-center text-xs" /><ChevronRight className="size-3.5 text-[#A27C2E]" /><span className="font-semibold text-[#705622]">公式總值</span></div></div>; }
function Condition({ label, value, onChange }: { label: string; value: "閒" | "莊" | "和"; onChange: (value: "閒" | "莊" | "和") => void }) { return <div className="rounded-xl border border-[#E6EAF0] bg-[#FCFDFE] p-4"><p className="text-sm font-bold text-[#15243B]">{label}</p><div className="mt-3 flex items-center gap-2"><Equal className="size-4 text-[#A27C2E]" /><select value={value} onChange={event => onChange(event.target.value as "閒" | "莊" | "和")} className="h-9 flex-1 rounded-md border border-[#E1E6ED] bg-white px-2 text-sm font-semibold text-[#40516A]"><option value="閒">預測：閒</option><option value="莊">預測：莊</option><option value="和">預測：和</option></select></div></div>; }
